// tests/bw-01-only-one-block-no-next-section.spec.js
//
// BW (Booking Windows) — Only one visible block: no next-block section.
// Covers scenario:
//   BW-01: Only current block shown (no next block)
//
// What this proves: when a class has only one visible block, the card
// renders a Book Current Block button but does NOT render the collapsible
// "Next Block" toggle. The toggle is only generated by buildCard() when
// getNextBlock() returns a non-null block (index.html line 1023).
//
// Target: Wednesday Beginner. In the seeded fixture this class has exactly
// one visible block (wed-upcoming). Friday also has only one visible block
// but is used by BW-06 — keeping Wed for BW-01 keeps the two specs cleanly
// separated.
//
// Read-only spec — no database state created. No afterEach needed.

const { test, expect } = require('@playwright/test');
const { APP_PATH } = require('./helpers/app-url');
const { getBlocksByRoles } = require('./helpers/fixture-lookup');

const APP_URL = process.env.TEST_APP_URL;

test.describe('BW-01 — Class with only one visible block has no next-block section', () => {
  test.skip(!APP_URL, 'TEST_APP_URL not set — BW specs require the app to be served.');

  test.beforeEach(async ({ page }) => {
    await page.goto(APP_PATH);
    await expect(
      page.locator('#test-mode-banner.on'),
      'TEST MODE banner is not visible — env switch is NOT active, aborting to protect production data'
    ).toBeVisible({ timeout: 5000 });
  });

  test('Wednesday card has Book Current Block button and no .next-blk-toggle', async ({ page }) => {
    // Pre-flight: confirm the fixture really has only one visible block for
    // Wednesday (class 2). If a future fixture change adds another block,
    // fail fast with a clear reason rather than a confusing selector failure.
    const { 'wed-upcoming': wedUpcoming } = await getBlocksByRoles(['wed-upcoming']);
    expect(wedUpcoming, 'wed-upcoming should resolve from fixture').toBeTruthy();

    const card = page.locator('.card').filter({
      has: page.locator('.card-when-day', { hasText: 'Wednesday' })
    }).first();
    await expect(card, 'expected a Wednesday class card').toBeVisible({ timeout: 10000 });

    // The card should have exactly one book button reading "Book Current Block".
    // (We tolerate "Current Block Full" / "Booking Closed" as future variants,
    // but assert NOT "Book Next Block" since that would mean a next-block
    // section was rendered.)
    const bookButtons = card.locator('button.book-btn');
    await expect(bookButtons).toHaveCount(1);
    const buttonText = (await bookButtons.first().textContent()).trim();
    expect(buttonText).toMatch(/Book Current Block|Current Block Full|Booking Closed/);
    expect(buttonText).not.toContain('Next Block');

    // The collapsible next-block toggle must NOT exist on this card.
    await expect(card.locator('.next-blk-toggle')).toHaveCount(0);
    // And no next-block body either (belt-and-braces).
    await expect(card.locator('.next-blk-body')).toHaveCount(0);
  });
});
